### ISSUE TITLE
Publish?

### ISSUE THREAD

**Issue by alexgorbatchev** [jsedlacek/browserify-autoprefixer#1]
Curious why this module isn't published?

**Comment by jsedlacek** [comment]
Hi @alexgorbatchev, I did not see a need to publish this to npm. I did this primarily for myself, the module does not have any docs and I do not have any experience with publishing to npm.

Would you be interested in helping me publish this to npm?

BTW you can install it even without publishing using `npm install jsedlacek/browserify-autoprefixer`.
